spring:
  application:
      name: service-openapi
  cloud:
    config:
      label: master
      profile: test
eureka:
  client:
      service-url:
        defaultZone: http://127.0.0.1:9999/eureka/






