info:
    version: 1.0.0
server:
  port: 8001
spring:
  application:
    name: cloud-gateway
  cloud:
    config:
      discovery:
        enabled: true
        service-id: cloud-config
      label: master
      profile: default
eureka:
  client:
      service-url:
        defaultZone: http://127.0.0.1:9999/eureka/
# spring-boot-actuator  spring-configuration-metadata.json
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - health
          - info
          - sessions
          - beans
          - env
          - threaddump
          - heapdump
          - configprops
          - httptrace
          - logfile
          - loggers
          - scheduledtasks
          - mappings
          - metrics

