server:
  port: 8889
info:
  app:
    version: 1.0.0
spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zingson/zengs-cloud.git
          default-label: master
          search-paths: _config/
          username:
          password:
eureka:
  client:
      service-url:
        defaultZone: http://127.0.0.1:9999/eureka/
# spring-boot-actuator  spring-configuration-metadata.json
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - health
          - info
          - sessions
          - beans
          - env
          - threaddump
          - heapdump
          - configprops
          - httptrace
          - logfile
          - loggers
          - scheduledtasks
          - mappings
          - metrics
