server:
  port: 8888
spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zingson/zengs-cloud.git
          search-paths: _config/
          username:
          password:
